version: "2"
services:
  dump_recreate_db:
    build:
      dockerfile: ./PostgresDockerfile
      context: .
    ports:
      - "5432:5432"
    volumes:
      - ./dump/:/docker-entrypoint-initdb.d/
    environment:
     - POSTGRES_DB=db 
     - POSTGRES_PASSWORD=this_is_not_a_secret
     - POSTGRES_USER=dbuser
