#! /bin/bash -e

#####################################
# Install homebrew
#####################################
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
