#! /bin/bash -e

#####################################
# Install homebrew
#####################################
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash -o ~/.git-completion.bash 


#####################################
# Install for mobile/web development
#####################################
#brew install nvm
#brew install watchman
nvm install 8

#####################################
# Install Debugging Tools
#####################################
brew install sqlite
brew install postgresql
brew install aws

#########################################
# Additional Tools for mobile development
#########################################
#sudo gem install cocoapods -v 1.3.1
#npm install -g react-native-cli
brew cask install ngrok

npm install -g npm@5.6.0
