#! /bin/bash -e

#####################################
# Install homebrew
#####################################
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"


#####################################
# Install for mobile/web development
#####################################
brew install nvm
brew install watchman
nvm install 6

#####################################
# Install Debugging Tools
#####################################
brew install sqlite
brew install postgresql

#########################################
# Additional Tools for mobile development
#########################################
sudo gem install cocoapods -v 1.3.1
npm install -g react-native-cli
brew cask install ngrok

npm install -g npm@3.10.10
